<script type="text/javascript">
(function() {
    function riskifiedBeaconLoad() {
        var session_id = "<?php echo $this->sessionId; ?>";
        var store_domain = "<?php echo $this->shopDomain; ?>";
        var version = "<?php echo $this->extensionVersion; ?>";
        var url = ('https:' == document.location.protocol ? 'https://' : 'http://') + "<?php echo $this->beaconUrl?>?shop="+store_domain+"&sid="+session_id+"&v="+version;
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = url;
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    }
    window.attachEvent ? window.attachEvent('onload', riskifiedBeaconLoad) : window.addEventListener('load', riskifiedBeaconLoad, false);
})();
</script>
