

<script type="text/javascript">
(function() {
    function riskifiedBeaconLoad() {
        var store_domain="<?php echo Mage::getStoreConfig('fullsection/full/domain',Mage::app()->getStore())?>";
        var url = "http://app.riskified.com/assets/beacon.js?shop="+store_domain;
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = url;
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    }
    window.attachEvent ? window.attachEvent('onload', riskifiedBeaconLoad) : window.addEventListener('load', riskifiedBeaconLoad, false);
})();
</script>
