<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2011 Riskified (http://www.riskified.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$all_active_methods = Mage::getModel('payment/config')->getActiveMethods();
$alreadySent = Mage::getModel('sales/order')->getCollection()->addFieldToFilter('is_sent_to_riskified', 1)->getSize();
$sendingOrdersToRiskified = Mage::getStoreConfig('riskified/cron/run_historical_orders', 0);
?>

<style type="text/css">
    .riskified-botton {
        font-family: Helvetica Neue;
        font-size: 23px;
        line-height: 25px;
        color: #FFF;
        background-color: #9bc47f;
        background: #9bc47f;
        padding: 5px 10px;
        border: 1px solid #828282;
        display: inline-block;
        text-decoration: none;
        width: 294px;
        text-align: center;
        font-weight: 300;
        letter-spacing: 0.05em;
        margin-bottom: 20px;
    }

    .riskified-botton:hover{
        background-color: #edd364;
        background: #edd364;
        text-decoration: none;
        color: #FFF;
    }
    .riskified-botton.send {
        margin-bottom: 10px;
    }

    .step-inner {
        display: inline-block;
        vertical-align: top;
        float: right;
    }

    .step-action {
        display: inline-block;
        float: right;
    }

    .step-wrapper {
        margin-top: 30px;
        padding-top: 30px;
        border-top: 1px solid #dedede;
        display: block;
        width: 800px;
        clear: both;
    }

    #send-historical-orders-message {
        font-family: Helvetica Neue, sans-serif;
        color : #ff0000;
        margin-bottom:30px;
        font-size: 16px;
    }

    .already-sent {
        margin-bottom: 30px;
        font-size: 16px;
        color: #1b6800;
    }

    .one {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.0s;
        animation: dot 1.3s infinite;
        animation-delay: 0.0s;
    }

    .two {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.2s;
        animation: dot 1.3s infinite;
        animation-delay: 0.2s;
    }

    .three {
        opacity: 0;
        -webkit-animation: dot 1.3s infinite;
        -webkit-animation-delay: 0.3s;
        animation: dot 1.3s infinite;
        animation-delay: 0.3s;
    }

    @-webkit-keyframes dot {
        0% {
            opacity: 0;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

    @keyframes dot {
        0% {
            opacity: 0;
        }
        50% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }

    #send-again {
        color: #000;
        font-weight: bolder;
        cursor: pointer;
    }

</style>

<script type="text/javascript">
    //<![CDATA[

    document.observe("dom:loaded", function() {
        var rhtml = '';
        var bottomHtml = '';
        rhtml += '<span id="riskified-logo" style="margin-top: 12px; margin-bottom: 19px;  display:block">';
        rhtml += '  <img width="204px" height="53px" src="<?php echo $this->getSkinUrl('images/riskified/logo.jpg'); ?>"/>';
        rhtml += '</span>';
        rhtml += '<div id="riskified-header" style="font-family:Helvetica Neue; font-size: 19px; line-height: 23px; color: #393536;">';
        rhtml += 'The Riskified extension has been installed.<br>To activate the extension please connect it to your Riskified account';
        rhtml += '</div>';

        var authToken = '<?php echo Mage::helper('full')->getAuthToken()?>';
        var shopDomain= '<?php echo Mage::helper('full')->getShopDomain()?>';

        var section = $$("#fullsection_full")[0];

        if (authToken.trim() || shopDomain.trim()) {
            rhtml = '<span id="riskified-logo" style="margin-top: 12px; margin-bottom: 19px;  display:block">  <img width="204px" height="53px" src="<?php echo $this->getSkinUrl('images/riskified/logo.jpg'); ?>"></span>';
            rhtml += '<div id="riskified-header" style="font-family:Helvetica Neue; font-size: 19px; line-height: 23px; color: #393536;margin-bottom: 25px;">The extension is connected to your Riskified account</div>';
            rhtml += '<a class="riskified-botton" style="margin-bottom:30px" href="//<?php echo Mage::helper('full/order')->getRiskifiedApp()?>" target="_blank">Go to Riskified App</a>';
            bottomHtml += '<a class="riskified-botton send" id="send-historical-orders" style="display:block;" href="javascript:void(0);">Send All Historical Orders</a>';
            bottomHtml += '<p id="send-historical-orders-message"<?php echo $sendingOrdersToRiskified ? 'style="display:block;"' : 'style="display:none;"'; ?>>Sending orders to Riskified<span class="one">.</span><span class="two">.</span><span class="three">.</span>​</p>';
            bottomHtml += '<p id="send-historical-orders-status" style="display:none;"></p>';
            <?php if($alreadySent): ?>
            bottomHtml += '<p class="already-sent"><span id="already-sent-count"><?php echo $alreadySent; ?></span> order(s) were sent in the past.<?php if(!$sendingOrdersToRiskified): ?> <span id="send-again"> Send All Again</span><?php endif; ?></p>';
            <?php endif; ?>
        }else{
            rhtml += '<span class="step-wrapper">';
            rhtml += '    <div class="step-title"  style="font-family:Helvetica Neue; font-size: 25px; line-height: 30px; color: #393536; display:inline-block">';
            rhtml += '    Create Your Account';
            rhtml += '        <span  style="margin-left: 20px;font-family:Helvetica Neue; font-size: 14px; line-height: 17px; color: #828282; padding: 5px; display:block">';
            rhtml += '             Already have an account? Fill the Shop Domain and Auth Token fields. ';
            rhtml += '        </span>';
            rhtml += '    </div>';
            rhtml += '    <span class="step-inner">';
            rhtml += '        <span class="step-action">';
            rhtml += '            <a class="riskified-botton" style="margin-top:13px"  href="http://www.riskified.com/?platform=magento#install-section" target="_blank">Create an account</a>';
            rhtml += '        </span>';
            rhtml += '    </span>';
            rhtml += '</span>';
            //$$(".entry-edit-head.collapseable")[0].style.display = "none";
        }
        htmlBody = rhtml;

        section.up().insert({top:htmlBody});
        section.up().insert(bottomHtml);

        $("send-historical-orders").observe('click', function(){
            sendRequest();
        });
        if($("send-again")) {
            $("send-again").observe('click', function() {
                sendRequest(true);
            });
        }
        var internal = null;
        function sendRequest(resend) {
            $('send-historical-orders-message').show();
            new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/riskifiedfull/sendHistoricalOrders"); ?>', {
                method:     'get',
                parameters : {
                    resend : resend
                },
                onSuccess : function(resp) {
                    var response = JSON.parse(resp.responseText);

                    if(response.success && !response.by_cron) {
                        $('send-historical-orders-status').show().update(response.message);
                        $('send-historical-orders-message').hide();
                    } else if(response.by_cron){
                        initUpdate();
                    }
                }
            });
        }

        function initUpdate() {
            internal = setInterval(getProgress, 5000);
        }

        function getProgress() {
            new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/riskifiedfull/sendHistoricalOrdersStatus"); ?>', {
                method:     'get',
                onCreate: function(request) {
                    Ajax.Responders.unregister(varienLoaderHandler.handler);
                },
                onSuccess : function(resp) {
                    Ajax.Responders.register(varienLoaderHandler.handler);
                    var response = JSON.parse(resp.responseText);
                    if (response.success) {
                        $('already-sent-count').update(response.total_sent);
                        if(response.status == 1) {
                            clearInterval(internal);
                        }
                    }
                }
            });
        }
    });

    //]]>
</script>

