<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2011 Excellence Technologies (http://www.excellencetechnologies.in)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php 
 $all_active_methods = Mage::getModel('payment/config')->getActiveMethods();
 $allkeys ='';
 foreach ($all_active_methods as $key => $value)
 {
 Ê$paymentTitle = Mage::getStoreConfig('payment/'.$key.'/title');
 Ê$methods[$key] = $paymentTitle;
 Ê$allkeys .= $key.",";
 }
?>
 
<style type="text/css">
    .riskified-botton {
        font-family: Helvetica Neue;
        font-size: 23px;
        line-height: 25px;
        color: #FFF;
        background-color: #9bc47f;
        padding: 5px 10px;
        border: 1px solid #828282;
        display: inline-block;
        text-decoration: none;
        width: 294px;
        text-align: center;
        font-weight: 300;
        letter-spacing: 0.05em;
        margin-bottom: 20px;

    }

    .riskified-botton:hover{
        background-color: #edd364;
    }

    .step-inner {
        display: inline-block;
        vertical-align: top;
        float: right;
    }

    .step-action {
        display: inline-block;
        float: right;
    }

    .step-wrapper {
        margin-top: 30px;
        padding-top: 30px;
        border-top: 1px solid #dedede;
        display: block;
        width: 800px
    }
    #activate-form input{
        display: block;
        width: 300px;
        line-height: 30px;
        font-size: 17px;
        margin-bottom: 10px;
        padding-left: 10px  ;
    }
    fieldset {
        background: #FFF;
    }
    
    .text-notice {
      font-weight: 300;
      font-size: 15px;
      color: #d15a2f;
      display: none;
      margin-top: 0px;
      margin-bottom: 0px;
      line-height: 0px;
      text-align: center;
    }
</style>

<script type="text/javascript">
//<![CDATA[
           
function activate(){
  var riskifiedShopDomain = $$("#riskified-shop-domain")[0].value;
  if (riskifiedShopDomain == ""){

  }
  var riskifiedPassword = $$("#riskified-password")[0].value;
  var generatedKey = "<?php sha1(microtime(true).mt_rand(10000,90000)); ?>";
  var keyInput = $$("#fullsection_full_key")[0].value;
  var keys = "<?php echo $allkeys ?>";
  new Ajax.Request('http://public-beta.herokuapp.com/magento/activate', {
    method: 'POST',
    parameters: "shop_url="+riskifiedShopDomain+"&password="+riskifiedPassword+"&auth_token="+generatedKey+"&gws="+keys ,
    onSuccess: 
      function(response) {
        $$("#magento-notice").hide()
      },
    onFailure: 
      function(response) {
        $$("#magento-notice").show()
      }
  });
}
document.observe("dom:loaded", function() {
	var rhtml = '';
  rhtml += '<span id="riskified-logo" style="margin-top: 12px; margin-bottom: 19px;  display:block">';
  rhtml += '  <img width="204px" height="53px" src="<?php echo $this->getSkinUrl('images/riskified/logo.jpg'); ?>"/>';
  rhtml += '</span>';
  rhtml += '<div id="riskified-header" style="font-family:Helvetica Neue; font-size: 19px; line-height: 23px; color: #393536;">';
  rhtml += '  The Riskified extension was successfully installed. <br>All that is left to do is to activate your extension and <br>connect it with a Riskified account';
  rhtml += '</div>';
  rhtml += '<span class="step-wrapper">';
  rhtml += '    <div class="step-title"  style="font-family:Helvetica Neue; font-size: 25px; line-height: 30px; color: #393536; display:inline-block">';
  rhtml += '    1. Create Your Account';
  rhtml += '        <span  style="margin-left: 20px;font-family:Helvetica Neue; font-size: 14px; line-height: 17px; color: #828282; padding: 5px; display:block">';
  rhtml += '            Already have an account? go to step #2';
  rhtml += '        </span>';
  rhtml += '    </div>';
  rhtml += '    <span class="step-inner">';
  rhtml += '        <span class="step-action">';
  rhtml += '            <a class="riskified-botton" style="margin-top:13px"  href="http://www.riskified.com/?platform=magento#install-section" target="_blank">Create an account</a>';
  rhtml += '        </span>';
  rhtml += '    </span>';
  rhtml += '</span>';
  rhtml += '<span class="step-wrapper">';
  rhtml += '    <div class="step-title"  style="font-family:Helvetica Neue; font-size: 25px; line-height: 30px; color: #393536; display:inline-block">';
  rhtml += '        2. Activate you extension';
  rhtml += '    </div>';
  rhtml += '    <span class="step-inner">';
  rhtml += '        <form id="activate-form">';
  rhtml += '            <input id="riskified-shop-domain" type="text" pattern="" placeholder="your-riskified.shop.domain">';
  rhtml += '            <input id="riskified-shop-password" type="password" pattern="" placeholder="your Riskified password">';
  rhtml += '        </form>';
  rhtml += '        <span class="text-notice" id="magento-notice">Shop url or password are incorrect</span>';
  rhtml += '        <span class="step-action">';
  rhtml += '            <a class="riskified-botton" href="javascript:activate()">Activate your account</a>';
  rhtml += '        </span>';
  rhtml += '    </span>';
  rhtml += '</span>';
  
     if (!document.getElementById("fullsection_full_activationstatus")) {
         return;
     }
     var keyRow = $$('#row_fullsection_full_key')
     if (keyRow.size()== 0){
       return;
     }else{
       keyRow = keyRow[0];
     }
     var mbody = keyRow.up();
     var mtable = mbody.up();
     mtable.hide();
     var section = mtable.up();
     section.setStyle({backgroundColor: '#FFF'});
     section.insert(rhtml);
     
});
   
//]]>
</script>